name: Bilibili Collection Update

on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-collection:
    runs-on: ubuntu-latest
    env:
      SESSDATA: ${{ secrets.SESSDATA }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSHTOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python Dependencies
        run: |
          pip install requests

      - name: Pull Latest Changes
        run: |
          git pull origin main
          
      - name: Run Bilibili Collection Update Script
        run: python get_video_info.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'Raccoon'
          git config --global user.email '1665651288@qq.com'
          git add .
          git commit -m "Updated Bilibili Collections"
          git push
